debug: false

server:
    port: 7776

spring:
    jpa:
        hibernate:
          ddl-auto: none
        show-sql: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://127.0.0.1:3306/spring-boot?useUnicode=true&useSSL=false&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 777
        schema: classpath:/sql/schema-mysql.sql
        data: classpath:/sql/data-mysql.sql


#        druid:
#            filters: stat,wall,log4j                      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#            maxActive: 20
#            initialSize: 0
#            maxWait: 60000                                # 配置获取连接等待超时的时间
#            minIdle: 1
#            timeBetweenEvictionRunsMillis: 60000          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#            minEvictableIdleTimeMillis: 300000            # 配置一个连接在池中最小生存的时间，单位是毫秒
#            validationQuery: select 'x'
#            testWhileIdle: true
#            testOnBorrow: false
#            testOnReturn: false
#            poolPreparedStatements: true
#            maxPoolPreparedStatementPerConnectionSize: 20
#            connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#            maxOpenPreparedStatements: 20
#
#            useGlobalDataSourceStat: true                 # 合并多个DruidDataSource的监控数据
    resources:
      cache-period: 15

mybatis:
    configuration:
        mapUnderscoreToCamelCase: true # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN 到经典 Java 属性名 aColumn 的类似映射。
    type-aliases-package: com.smart.service.template.mapper.model

#TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
#logging:
#    level:
#        root: WARN
#        com.smart: DEBUG
#        static: DEBUG

# 实体类的包
#    mapper-locations: classpath:mapper/**/*.xml                   # mapper的xml文件
